app:
  build: .
  volumes:
    - ./:/go/src/github.com/talon-one/talon-access-proxy
    - /usr/sbin/buildkite-agent:/usr/bin/buildkite-agent
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
